jobs:
  - name: input
    type: manifest
    steps:
      - TASK: managed
  - name: out-2
    type: manifest
    steps:
      - TASK: managed
      - IN: input
  - name: out-4
    type: manifest
    steps:
      - TASK: managed
      - IN: input
  - name: out-3
    type: manifest
    steps:
      - TASK: managed
      - IN: input
  - name: out-2a
    type: manifest
    steps:
      - TASK: managed
      - IN: image
  - name: out-4a
    type: manifest
    steps:
      - TASK: managed
      - IN: image
  - name: out-3a
    type: manifest
    steps:
      - TASK: managed
      - IN: image
  - name: input-a
    type: manifest
    steps:
      - TASK: managed
      - OUT: image

resources:
  - name: image
    type: image
    integration: shipdeploy
    versionTemplate:
      sourceName: asd
      versionName: asd
